In [207]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [208]:
df= pd.read_csv("../data/1. raw/smoking_prediction.xlsx - smoking_prediction.csv")

In [209]:
df.head(10)

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking
0,0,F,40,155,60,3.38,0.04,0.04,0.04,0.04,...,0.51,0.04,0.00,0.75,0.79,1.13,Y,0,Y,0
1,1,F,40,160,60,3.38,0.01,0.00,0.04,0.04,...,0.50,0.04,0.00,0.92,0.79,0.75,Y,0,Y,0
2,2,M,55,170,60,3.33,0.01,0.01,0.04,0.04,...,0.63,0.04,0.04,0.88,0.67,0.92,Y,0,N,1
3,3,M,40,165,70,3.67,0.05,0.05,0.04,0.04,...,0.59,0.04,0.04,0.79,1.08,0.75,Y,0,Y,0
4,4,F,40,155,60,3.58,0.04,0.04,0.04,0.04,...,0.50,0.04,0.00,0.67,0.58,0.92,Y,0,N,0
5,5,M,30,180,75,3.54,0.04,0.04,0.04,0.04,...,0.67,0.04,0.04,0.75,1.13,1.38,Y,0,Y,0
6,6,M,40,160,60,3.55,0.04,0.04,0.04,0.04,...,0.71,0.04,0.00,0.88,1.13,1.63,Y,1,Y,1
7,7,M,45,165,90,4.00,0.04,0.04,0.04,0.04,...,0.63,0.04,0.04,1.58,2.96,4.63,Y,0,Y,0
8,9,F,50,150,60,3.54,0.00,0.01,0.04,0.04,...,0.55,0.04,0.01,1.29,1.29,0.58,Y,0,N,0
9,10,M,45,175,75,3.71,0.04,0.04,0.04,0.04,...,0.67,0.04,0.01,1.08,1.00,2.63,Y,0,N,0

In [210]:
X=df.drop(columns=["smoking", "ID", "oral"]) # Quitamos la columa oral, ya que tiene todos los valores iguales.
y=df["smoking"]

In [211]:
X

,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),systolic,...,HDL,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,dental caries,tartar
0,F,40,155,60,3.38,0.04,0.04,0.04,0.04,4.75,...,3.04,5.25,0.51,0.04,0.00,0.75,0.79,1.13,0,Y
1,F,40,160,60,3.38,0.01,0.00,0.04,0.04,4.96,...,1.75,5.29,0.50,0.04,0.00,0.92,0.79,0.75,0,Y
2,M,55,170,60,3.33,0.01,0.01,0.04,0.04,5.75,...,2.29,6.29,0.63,0.04,0.04,0.88,0.67,0.92,0,N
3,M,40,165,70,3.67,0.05,0.05,0.04,0.04,4.17,...,1.88,9.42,0.59,0.04,0.04,0.79,1.08,0.75,0,Y
4,F,40,155,60,3.58,0.04,0.04,0.04,0.04,5.00,...,2.58,4.46,0.50,0.04,0.00,0.67,0.58,0.92,0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,M,50,160,55,2.96,0.00,0.01,0.04,0.04,5.08,...,2.63,3.04,0.55,0.04,0.04,0.96,0.58,0.92,0,Y
49996,M,30,170,70,3.33,0.05,0.04,0.04,0.04,4.67,...,2.25,3.21,0.63,0.04,0.01,1.08,1.21,0.75,1,Y
49997,M,20,165,65,3.54,0.05,0.05,0.04,0.04,5.21,...,1.96,2.21,0.67,0.04,0.01,1.46,1.46,2.92,0,Y
49998,F,60,160,45,2.96,0.00,0.00,0.04,0.04,4.92,...,2.58,4.13,0.58,0.04,0.00,0.79,0.67,1.04,1,Y
49999,M,45,170,80,4.00,0.05,0.04,0.04,0.04,5.63,...,2.75,5.04,0.63,0.04,0.04,1.17,1.71,2.58,1,N

In [212]:
# dividimos X e y en conjuntos de entrenamiento (80%) y test (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42, 
    stratify=y
)

In [213]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40000 entries, 7883 to 32714
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               40000 non-null  object
 1   age                  40000 non-null  int64
 2   height(cm)           40000 non-null  int64
 3   weight(kg)           40000 non-null  int64
 4   waist(cm)            40000 non-null  float64
 5   eyesight(left)       40000 non-null  float64
 6   eyesight(right)      40000 non-null  float64
 7   hearing(left)        40000 non-null  float64
 8   hearing(right)       40000 non-null  float64
 9   systolic             40000 non-null  float64
 10  relaxation           40000 non-null  float64
 11  fasting blood sugar  40000 non-null  float64
 12  Cholesterol          40000 non-null  float64
 13  triglyceride         40000 non-null  float64
 14  HDL                  40000 non-null  float64
 15  LDL                  40000 non-null  float64
 16  hemoglobin           40000 non-null  float64
 17  Urine protein        40000 non-null  float64
 18  serum creatinine     40000 non-null  float64
 19  AST                  40000 non-null  float64
 20  ALT                  40000 non-null  float64
 21  Gtp                  40000 non-null  float64
 22  dental caries        40000 non-null  int64
 23  tartar               40000 non-null  object
dtypes: float64(18), int64(4), object(2)
memory usage: 7.6+ MB

In [214]:
num_cols = X_train.select_dtypes(include=["int64", "float64"]).columns.tolist() # Gaurda las columnas numéricas tipo int64 y float64
cat_cols = X_train.select_dtypes(include=["object"]).columns.tolist() # Guardas las columnas numéricas tipo objets

In [215]:
cat_cols

['gender', 'tartar']

In [216]:
from sklearn.preprocessing import OneHotEncoder

In [217]:
ohe=OneHotEncoder(handle_unknown="ignore",sparse_output=False) # creamos un encoder

In [218]:
ohe.fit(X_train[cat_cols]) #Fiteamos el encoder solo con X_train

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [219]:
# transformamos las columnas categoricas. Convertimos las columnas categóricas de X_train y X_test en columnas de 0s y 1s.
X_train_ohe=ohe.transform(X_train[cat_cols])
X_test_ohe=ohe.transform(X_test[cat_cols])

In [220]:
X_test_ohe

array([[0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       ...,
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.]])

In [221]:
X_train_ohe

array([[1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       ...,
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.]])

In [222]:
ohe_columns = ohe.get_feature_names_out(cat_cols) # obtenemos los nombres de las columnas generadas con OHE.

In [223]:
ohe_columns # revisamos si se crearon las columnas.

array(['gender_F', 'gender_M', 'tartar_N', 'tartar_Y'], dtype=object)

In [224]:
X_train_ohe_df = pd.DataFrame(X_train_ohe, columns=ohe_columns, index=X_train.index) # se crean las columnas de ohe de Train en un "nuevo" dataSet

In [225]:
X_train_ohe_df

       gender_F  gender_M  tartar_N  tartar_Y
7883        1.0       0.0       0.0       1.0
3451        1.0       0.0       1.0       0.0
3495        0.0       1.0       1.0       0.0
49723       0.0       1.0       1.0       0.0
34452       0.0       1.0       1.0       0.0
...         ...       ...       ...       ...
48892       1.0       0.0       0.0       1.0
25727       1.0       0.0       1.0       0.0
18911       0.0       1.0       1.0       0.0
25680       1.0       0.0       1.0       0.0
32714       1.0       0.0       0.0       1.0

[40000 rows x 4 columns]

In [226]:
X_test_ohe_df = pd.DataFrame(X_test_ohe, columns=ohe_columns, index=X_test.index) # se crean las columnas de ohe de Test en un "nuevo" dataSet

In [227]:
X_test_ohe_df

       gender_F  gender_M  tartar_N  tartar_Y
22351       0.0       1.0       1.0       0.0
18366       0.0       1.0       0.0       1.0
48995       1.0       0.0       1.0       0.0
46004       1.0       0.0       0.0       1.0
47523       0.0       1.0       1.0       0.0
...         ...       ...       ...       ...
49248       0.0       1.0       0.0       1.0
46858       0.0       1.0       0.0       1.0
8132        1.0       0.0       1.0       0.0
37443       0.0       1.0       1.0       0.0
25412       0.0       1.0       1.0       0.0

[10000 rows x 4 columns]

In [228]:
#Eliminamos las columnas categóricas de Xtrain y Xtest. nos quedamos solo con las numéricas.
X_train_num = X_train[num_cols]
X_test_num = X_test[num_cols]

In [229]:
#Ahora concateramos el Dataset original ( sin las categoricas) con los "dataset nuevos" con las columnas de OHE.
X_train_final = pd.concat([X_train_num, X_train_ohe_df], axis=1)
X_test_final = pd.concat([X_test_num, X_test_ohe_df], axis=1)

In [230]:
X_train_final.shape

(40000, 26)

In [231]:
X_train_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40000 entries, 7883 to 32714
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  40000 non-null  int64
 1   height(cm)           40000 non-null  int64
 2   weight(kg)           40000 non-null  int64
 3   waist(cm)            40000 non-null  float64
 4   eyesight(left)       40000 non-null  float64
 5   eyesight(right)      40000 non-null  float64
 6   hearing(left)        40000 non-null  float64
 7   hearing(right)       40000 non-null  float64
 8   systolic             40000 non-null  float64
 9   relaxation           40000 non-null  float64
 10  fasting blood sugar  40000 non-null  float64
 11  Cholesterol          40000 non-null  float64
 12  triglyceride         40000 non-null  float64
 13  HDL                  40000 non-null  float64
 14  LDL                  40000 non-null  float64
 15  hemoglobin           40000 non-null  float64
 16  Urine protein        40000 non-null  float64
 17  serum creatinine     40000 non-null  float64
 18  AST                  40000 non-null  float64
 19  ALT                  40000 non-null  float64
 20  Gtp                  40000 non-null  float64
 21  dental caries        40000 non-null  int64
 22  gender_F             40000 non-null  float64
 23  gender_M             40000 non-null  float64
 24  tartar_N             40000 non-null  float64
 25  tartar_Y             40000 non-null  float64
dtypes: float64(22), int64(4)
memory usage: 8.2 MB

### Escalado de los datos

In [232]:
from sklearn.preprocessing import StandardScaler

In [233]:
scaler= StandardScaler() # creamos un escalador.

In [234]:
scaler.fit(X_train_final[num_cols]) #Fiteamos solo en train en las columnas numéricas.

StandardScaler()

In [235]:
# Hacemos una copia para no modificar X_train_final y X_test_final originales
X_train_final_scaled = X_train_final.copy()
X_test_final_scaled = X_test_final.copy()

In [236]:
X_train_final_scaled[num_cols] = scaler.transform(X_train_final[num_cols]) # se aplica en las columnas numéricas el escalado aprendido a X_train_final

In [237]:
X_test_final_scaled[num_cols]= scaler.transform(X_test_final[num_cols])

Guardado de los objetos entrenados

In [238]:
import joblib

In [239]:
joblib.dump(ohe, "../data/4. objetos entrenados/ohe.pkl")
joblib.dump(scaler, "../data/4. objetos entrenados/scaler.pkl")
joblib.dump(num_cols, "../data/4. objetos entrenados/num_cols.pkl")
joblib.dump(cat_cols, "../data/4. objetos entrenados/cat_cols.pkl")

['../data/4. objetos entrenados/cat_cols.pkl']

In [240]:
joblib.dump(X_train_final.columns.tolist(), "../data/4. objetos entrenados/feature_columns.pkl")

['../data/4. objetos entrenados/feature_columns.pkl']

In [241]:
# Guardamos los datasets procesados para usarlos en el notebook de entrenamiento
X_train_final_scaled.to_csv("../data/2. processed/X_train.csv", index=False)
X_test_final_scaled.to_csv("../data/2. processed/X_test.csv", index=False)
y_train.to_csv("../data/2. processed/y_train.csv", index=False)
y_test.to_csv("../data/2. processed/y_test.csv", index=False)